### ISSUE TITLE
Problem with weekday calculation

### ISSUE THREAD

**Issue by mihammer97** [sthiele/asp-date-lib#1]
Some Values for the weekdays are wrong eg. 

![image](https://user-images.githubusercontent.com/62878987/77897880-8e779680-727a-11ea-95a3-58b2f5c2ec13.png)
 
This Problem occurs, because the following rule is not considered : 
![image](https://user-images.githubusercontent.com/62878987/77898177-0c3ba200-727b-11ea-99ed-630844ad8e48.png)
(https://en.wikipedia.org/wiki/Determination_of_the_day_of_the_week)

Here, w is the Weekday variable in the date_weekday Atom. 

Possible solution: 
![image](https://user-images.githubusercontent.com/62878987/77898497-89671700-727b-11ea-873d-a3381e4a0fab.png)

Uploaded fixed date-lib.lp as .txt, because .lp-files cant be uploaded here:

[date-lib_fixed.txt](https://github.com/potassco/asp-date-lib/files/4401959/date-lib_fixed.txt)

**Comment by sthiele** [comment]
Thank you for your report.
I'm currently maintaining asp-date-lib, maybe the original author @peschue can comment on this issue. In any case, as you already have a solution it would be very helpful if you could [open a pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by peschue** [comment]
I wonder if another, simpler solution would be to just always add 7 before the modulo operation?

I am quite sure I already had this in the code, at least in one place such an addition was necessary. Maybe I missed it in another place.

**Comment by mihammer97** [comment]
Yes, I think this would be the better solution.

**Comment by MaxOstrowski** [comment]
Did someone followed this up ?
Just wanted to open a PR for this as I stumbled over the same problem.

**Comment by sthiele** [comment]
No, would be happy about a PR.
